module.exports = {
    charCreateSuccess: require('./CharCreateSuccess'),
         charSelected: require('./CharSelected'),
       charSelectInfo: require('./CharSelectInfo'),
        charTemplates: require('./CharTemplates'),
             itemList: require('./ItemList'),
        logoutSuccess: require('./LogoutSuccess'),
       moveToLocation: require('./MoveToLocation'),
              npcInfo: require('./NpcInfo'),
            questList: require('./QuestList'),
              restart: require('./Restart'),
          sitAndStand: require('./SitAndStand'),
         socialAction: require('./SocialAction'),
              sunrise: require('./Sunrise'),
             userInfo: require('./UserInfo'),
         versionCheck: require('./VersionCheck'),
           walkAndRun: require('./WalkAndRun'),
};
