module.exports = {
           addShortcut: require('./AddShortcut'),
     charCreateSuccess: require('./CharCreateSuccess'),
          charSelected: require('./CharSelected'),
        charSelectInfo: require('./CharSelectInfo'),
         charTemplates: require('./CharTemplates'),
            cipherInit: require('./CipherInit'),
        destDeselected: require('./DestDeselected'),
          destSelected: require('./DestSelected'),
             itemsList: require('./ItemsList'),
         logoutSuccess: require('./LogoutSuccess'),
        moveToLocation: require('./MoveToLocation'),
             questList: require('./QuestList'),
               restart: require('./Restart'),
               showMap: require('./ShowMap'),
           sitAndStand: require('./SitAndStand'),
            skillsList: require('./SkillsList'),
          skillStarted: require('./SkillStarted'),
          socialAction: require('./SocialAction'),
                 speak: require('./Speak'),
              stopMove: require('./StopMove'),
               sunrise: require('./Sunrise'),
    teleportToLocation: require('./TeleportToLocation'),
              userInfo: require('./UserInfo'),
            walkAndRun: require('./WalkAndRun')
};
